#!/bin/bash

time semio-interpret compiler/{common.sio,number.sio,char.sio,string.sio,list.sio,optional.sio,comparable.sig,map.sig,ref.sio,source_code_position.sio,with_positions.sio,unbound.sig,unbound.sio,typed.sig,dynamics.sio}
